// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8WOXuwNSstXiOk3V45Go7Ee9sGccLLzM',
    appId: '1:918739558823:web:e6b1b8da7884acde85d682',
    messagingSenderId: '918739558823',
    projectId: 'fluttercommerce-ee1a5',
    authDomain: 'fluttercommerce-ee1a5.firebaseapp.com',
    storageBucket: 'fluttercommerce-ee1a5.firebasestorage.app',
    measurementId: 'G-F2JSBGJN0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk2Zz4aoNci9t68Gw7vMk7cTyp4Tl51GY',
    appId: '1:918739558823:android:3455434550d1258485d682',
    messagingSenderId: '918739558823',
    projectId: 'fluttercommerce-ee1a5',
    storageBucket: 'fluttercommerce-ee1a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnwdVExbgBnAucgN1bDSJLrQ7SMZPfTXM',
    appId: '1:918739558823:ios:766a1a6714ec47cb85d682',
    messagingSenderId: '918739558823',
    projectId: 'fluttercommerce-ee1a5',
    storageBucket: 'fluttercommerce-ee1a5.firebasestorage.app',
    iosBundleId: 'com.example.fluttercommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnwdVExbgBnAucgN1bDSJLrQ7SMZPfTXM',
    appId: '1:918739558823:ios:766a1a6714ec47cb85d682',
    messagingSenderId: '918739558823',
    projectId: 'fluttercommerce-ee1a5',
    storageBucket: 'fluttercommerce-ee1a5.firebasestorage.app',
    iosBundleId: 'com.example.fluttercommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8WOXuwNSstXiOk3V45Go7Ee9sGccLLzM',
    appId: '1:918739558823:web:a13c85501ffb253e85d682',
    messagingSenderId: '918739558823',
    projectId: 'fluttercommerce-ee1a5',
    authDomain: 'fluttercommerce-ee1a5.firebaseapp.com',
    storageBucket: 'fluttercommerce-ee1a5.firebasestorage.app',
    measurementId: 'G-2CYXMNVRGN',
  );
}
